apiVersion: batch/v1
kind: Job
metadata:
  name: pg-restore
spec:
  template:
    spec:
      containers:
      - name: pg-restore
        image: postgres:12.7
        command: 
        - sh 
        - -c 
        - sleep 1m && bash -x /pgscripts/pro-pg-xml-restore.sh;
        env:
        - name: PGPASSWORD
          value: docker
        - name: PGUSER
          value: postgres
        volumeMounts:
        - name: hk-aliyun-nas-pvc
          mountPath: /mnt
        - name: pgscripts
          mountPath: /pgscripts
      restartPolicy: Never
      volumes:
      - name: hk-aliyun-nas-pvc
        persistentVolumeClaim:
          claimName: hk-aliyun-nas-pvc
      - name: pgscripts
        configMap:
          name: pgscripts
  backoffLimit: 0