resources:
- job.yaml

namespace: timescaledb

namePrefix: restore-job-all-

configMapGenerator:
- name: pgscripts
  files:
  - ./scripts/prd-pgdata-backup.sh
  - ./scripts/pro-pg-restore.sh
  - ./scripts/pro-pg-xml-backup.sh
  - ./scripts/pro-pg-xml-restore.sh

generatorOptions:
  disableNameSuffixHash: true
