apiVersion: v1
kind: Service
metadata:
  name: custom-redis-standalone
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.11.246"
spec:
  ports:
  - name: redis
    port: 32099
    targetPort: redis
  type: LoadBalancer
  loadBalancerIP: 192.168.11.246