apiVersion: v1
kind: Service
metadata:
  name: oms-prd-nginx-ingress-nlb
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-east-1:328162702476:certificate/bc5e1a27-ca5e-4bc7-9e55-b35a7e15600c
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: >-
      map-migrated-cnmap=d-server-0067yxz39nth5o,map-migrated-project-id=GCR-Migration-2021-398,team=algo
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    service.beta.kubernetes.io/aws-load-balancer-name: algo-oms-prd-nginx-ingress-nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-subnets: 	subnet-0de1d566137ba344a, subnet-0a9fb80235b63192a
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  loadBalancerClass: service.k8s.aws/nlb