apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hk-office-nfs-share-monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: hk-office-nfs-share-monitoring
  storageClassName: ''
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hk-office-nfs-share-monitoring
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: algo-nas.aqumon.com
    path: /volume1/nfs_share
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - tcp
    - vers=3.11
    - nolock
  volumeMode: Filesystem