apiVersion: v1
kind: ConfigMap
metadata:
  name: zkui-configmap
data:
  config.cfg: |
    #Server Port
    serverPort=9090
    #Comma seperated list of all the zookeeper servers
    zkServer=172.31.74.188:2181,192.168.11.62:2181,172.19.247.50:2181
    #Http path of the repository. Ignore if you dont intent to upload files from repository.
    scmRepo=http://myserver.com/@rev1=
    #Path appended to the repo url. Ignore if you dont intent to upload files from repository.
    scmRepoPath=//appconfig.txt
    #if set to true then userSet is used for authentication, else ldap authentication is used.
    ldapAuth=false
    ldapDomain=mycompany,mydomain
    #ldap authentication url. Ignore if using file based authentication.
    ldapUrl=ldap://<ldap_host>:<ldap_port>/dc=mycom,dc=com
    #Specific roles for ldap authenticated users. Ignore if using file based authentication.
    ldapRoleSet={"users": [{ "username":"domain\\user1" , "role": "ADMIN" }]}
    userSet = {"users": [{ "username":"admin" , "password":"algo2020","role": "ADMIN" },{ "username":"appconfig" , "password":"appconfig","role": "USER" }]}
    #Set to prod in production and dev in local. Setting to dev will clear history each time.
    env=prod
    jdbcClass=org.h2.Driver
    jdbcUrl=jdbc:h2:zkui
    jdbcUser=root
    jdbcPwd=manager
    #If you want to use mysql db to store history then comment the h2 db section.
    #jdbcClass=com.mysql.jdbc.Driver
    #jdbcUrl=jdbc:mysql://localhost:3306/zkui
    #jdbcUser=root
    #jdbcPwd=manager
    loginMessage=
    #session timeout 5 mins/300 secs.
    sessionTimeout=999999999
    #Default 5 seconds to keep short lived zk sessions. If you have large data then the read will take more than 30 seconds so increase this accordingly. 
    #A bigger zkSessionTimeout means the connection will be held longer and resource consumption will be high.
    zkSessionTimeout=5
    #Block PWD exposure over rest call.
    blockPwdOverRest=false
    #ignore rest of the props below if https=false.
    https=false
    keystoreFile=/home/user/keystore.jks
    keystorePwd=password
    keystoreManagerPwd=password
    # The default ACL to use for all creation of nodes. If left blank, then all nodes will be universally accessible
    # Permissions are based on single character flags: c (Create), r (read), w (write), d (delete), a (admin), * (all)
    # For example defaultAcl={"acls": [{"scheme":"ip", "id":"192.168.1.192", "perms":"*"}, {"scheme":"ip", id":"192.168.1.0/24", "perms":"r"}]
    defaultAcl=
    # Set X-Forwarded-For to true if zkui is behind a proxy
    X-Forwarded-For=false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zkui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zkui 
  template:
    metadata:
      labels:
        app: zkui
    spec:
      imagePullSecrets:
      - name: algo-dockerhub-regcred
      containers:
        - name: zkui
          image: algo-dockerhub.aqumon.com/lib/zkui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /var/app/config.cfg
              name: configmap
              subPath: config.cfg
      volumes:
        - name: configmap
          configMap:
            name: zkui-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: zkui
spec:
  ports:
    - port: 80
      targetPort: 9090
      name: zkui
  selector:
    app: zkui
  type: ClusterIP