apiVersion: v1
kind: Service
metadata:
  name: redisinsight
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.11.246"
spec:
  ports:
  - name: web
    port: 18001
    targetPort: 8001
  type: LoadBalancer
  loadBalancerIP: 192.168.11.246