image:
  repository: timescale/timescaledb-ha
  tag: pg12.7-ts2.4-latest
secrets:
  pgbackrest:
    PGBACKREST_REPO1_S3_REGION: "ap-east-1"
    PGBACKREST_REPO1_S3_KEY: "AKIAUY2AFOSGIWRWNIEM"
    PGBACKREST_REPO1_S3_KEY_SECRET: "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"
    PGBACKREST_REPO1_S3_BUCKET: "aqm-algo-pgbackup"
    PGBACKREST_REPO1_S3_ENDPOINT: "s3-ap-east-1.amazonaws.com"
resources:
  limits:
    cpu: 7.5
    memory: 29Gi
  requests:
    cpu: 5
    memory: 13Gi
sharedMemory:
  useMount: true
patroni:
  bootstrap:
    dcs:
      postgresql:
        parameters:
          # max_wal_size: 400GB  # 80% of the Volume Size
          max_replication_slots: 4000
          max_connections: 256
          wal_keep_segments: 2000
          # wal_compression: on
          # archive_cleanup_command: pg_archivecleanup /var/lib/postgresql/wal/pg_wal %r
          # archive_cleanup_command: find /var/lib/postgresql/wal/pg_wal -mtime +7 -delete
          work_mem: 64MB
          timescaledb.restoring: on
          log_timezone: Asia/Shanghai
loadBalancer:
  enabled: false
replicaCount: 3
persistentVolumes:
  data:
    size: 1Ti
    storageClass: gp2
  wal:
    size: 100Gi
    storageClass: gp2
  tablespaces:
    xmlspace:
      size: 1Ti
      storageClass: gp2
prometheus:
  enabled: true
  image:
    tag: latest
# bootstrapFromBackup:
#   enabled: True
#   repo1-path: /timescaledb/datamaster
backup:
  enabled: true
  # utc
  jobs:
    - name: full-weekly
      type: full
      schedule: "0 14 * * 6"
    - name: differential-daily
      type: diff
      schedule: "30 20 * * *"
    - name: incremental-daily
      type: incr
      schedule: "30 21 * * *"
timescaledbTune:
  enabled: true
  args:
    max-conns: 256
    cpus: 9
    memory: 24GB
tolerations:
- key: node_type
  operator: Equal
  value: 2xlarge
  effect: NoSchedule
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 70 
        preference:
          matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              values:
                - hk-algo-prd-eks-cluster-workernodes-1b-2xlarge
serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  enabled: false
  portName: metrics
  path: /metrics
  interval: 10s
  # scrapeTimeout: 30s
  # Specifies namespace, where ServiceMonitor should be installed
  # namespace: monitoring
  # labels:
  #   release: prometheus
  # honorLabels: true
  # metricRelabelings: []
  # targetLabels:
  #   - foo