apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.11.246"
spec:
  ports:
  - name: http
    port: 32553
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.11.246