apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-mirror-vs
  namespace: playground
spec:
  hosts:
    - web-service.playground.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-service.playground.svc.cluster.local
        subset: v1
      weight: 100
    mirror:
      host: web-service.playground.svc.cluster.local
      subset: v2
    mirrorPercentage:
      value: 100.0
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destinationrule
  namespace: playground
spec:
  host: web-service.playground.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2