apiVersion: v1
kind: Secret
metadata:
  name: algo-dockerhub-regcred
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJhbGdvLWRvY2tlcmh1Yi5hcXVtb24uY29tIjp7InVzZXJuYW1lIjoiYXF1bW9uIiwicGFzc3dvcmQiOiJhcXVtb24yMDUwIiwiYXV0aCI6IllYRjFiVzl1T21GeGRXMXZiakl3TlRBPSJ9fX0=
type: kubernetes.io/dockerconfigjson
