apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      name: kafka-exportrer
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter
        args:
        - --kafka.server=b-1.bjalgopmsk.9eaz3q.c3.kafka.cn-north-1.amazonaws.com.cn:9092 
        - --kafka.server=b-2.bjalgopmsk.9eaz3q.c3.kafka.cn-north-1.amazonaws.com.cn:9092 
        - --kafka.server=b-3.bjalgopmsk.9eaz3q.c3.kafka.cn-north-1.amazonaws.com.cn:9092
        ports:
        - name: metrics
          containerPort: 9308
        resources: {}
        imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate