resource "aws_db_instance" "hk-algo-d-rds-mysql" {
  allocated_storage                     = "20"
  auto_minor_version_upgrade            = "true"
  availability_zone                     = "ap-east-1b"
  backup_retention_period               = "7"
  backup_window                         = "19:00-20:00"
  ca_cert_identifier                    = "rds-ca-rsa2048-g1"
  copy_tags_to_snapshot                 = "true"
  customer_owned_ip_enabled             = "false"
  db_subnet_group_name                  = "${aws_db_subnet_group.hk-algo-d-rds-subnet.name}"
  deletion_protection                   = "true"
  enabled_cloudwatch_logs_exports       = ["slowquery"]
  engine                                = "mysql"
  engine_version                        = "8.0.28"
  iam_database_authentication_enabled   = "false"
  identifier                            = "hk-algo-d-rds-mysql"
  instance_class                        = "db.t3.medium"
  iops                                  = "0"
  license_model                         = "general-public-license"
  maintenance_window                    = "sat:20:00-sat:21:00"
  max_allocated_storage                 = "1000"
  monitoring_interval                   = "60"
  monitoring_role_arn                   = "arn:aws:iam::328162702476:role/rds-monitoring-role"
  multi_az                              = "false"
  option_group_name                     = "default:mysql-8-0"
  parameter_group_name                  = "default-mysql8-tz8"
  performance_insights_enabled          = "true"
  performance_insights_retention_period = "7"
  port                                  = "3306"
  publicly_accessible                   = "true"
  storage_encrypted                     = "true"
  storage_type                          = "gp2"
  username                              = "aqumon"
  password                              = "koH9aNPRXjv9Hd"

  tags = {
    map-migrated-project-id = "GCR-Migration-2021-398"
    map-migrated-cnmap = "d-server-0067yxz39nth5o"
  }
}
