apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-aliyun-nas
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: 12b63749986-vvr1.cn-hongkong.nas.aliyuncs.com
    path: /c03-middleware
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-aliyun-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ''
  volumeMode: Filesystem