# apiVersion: v1
# kind: Service
# metadata:
#   name: registry-ui
#   annotations:
#     metallb.universe.tf/allow-shared-ip: key-to-share-192.168.11.246
# spec:
#   selector:
#     app: registry-ui
#   ports:
#   - port: 3001
#     targetPort: registry-ui
#   type: LoadBalancer
# ---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  annotations:
    metallb.universe.tf/allow-shared-ip: key-to-share-192.168.11.246
spec:
  selector:
    app: docker-registry-test
  ports:
  - port: 5000
    targetPort: docker-registry
  type: ClusterIP