---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-6nnnfel6quwwiicdhkinx"
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: ingress-kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-6nnnfel6quwwiicdhkinx"
spec:
  type: LoadBalancer
  ports:
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: ingress-kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-metrics
  namespace: kong
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-6nnnfel6quwwiicdhkinx"
spec:
  type: LoadBalancer
  ports:
  - name: metrics
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    app: ingress-kong