# apiVersion: v1
# kind: Service
# metadata:
#   name: timescaledb-only-one
# spec:
#   ports:
#   - name: db
#     port: 5432
#     targetPort: db
#     nodePort: 32632
#   type: NodePort
# ---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb-only-one-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.11.246"
spec:
  ports:
  - name: db
    port: 5432
    targetPort: db
  type: LoadBalancer
  loadBalancerIP: 192.168.11.246