apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: grafana
        resources:
          requests:
            cpu: 40m
            memory: 500Mi
        env: 
        - name: GF_INSTALL_PLUGINS
          value: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,redis-app,grafana-image-renderer
        - name: GF_SERVER_ROOT_URL
          value: "https://algo-internal.aqumon.com/grafana"
        # - name: GF_DEFAULT_FORCE_MIGRATION
        #   value: "true"
        - name: GF_ALERTING_ENABLED
          value: "false"
        - name: GF_UNIFIED_ALERTING_ENABLED
          value: "true"
        # - name: GF_SERVICE_SYSTEMCALLFILTER
        #   value: ""
        # - name: GF_SERVICE_MEMORYDENYWRITEEXECUTE
        #   value: "false"
        - name: TZ
          value: Asia/Shanghai
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s/grafana"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        envFrom:
        - secretRef:
            name: secret-grafana-env