apiVersion: v1
kind: Service
metadata:
  name: datamaster-replica
  namespace: timescaledb
  labels:
    app: datamaster-timescaledb
    cluster-name: datamaster
    role: replica
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: datamaster-timescaledb
    cluster-name: datamaster
    role: replica
  type: NodePort