apiVersion: v1
kind: Service
metadata:
  name: dm-slave
  namespace: timescaledb
  labels:
    app: dm-timescaledb
    cluster-name: dm
    role: replica
    type: lb
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-3nslhvzs6dfzmn71z71y9
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 25432
      targetPort: postgresql
  selector:
    app: dm-timescaledb
    cluster-name: dm
    role: replica
  type: LoadBalancer