apiVersion: v1
kind: Service
metadata:
  name: dm-stg-slave
  labels:
    role: replica
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-3nslhvzs6dfzmn71z71y9
spec:
  ports:
  - name: postgresql
    port: 36431
    targetPort: postgresql
  selector:
    app: stg-timescaledb
    cluster-name: stg
    role: replica
  type: LoadBalancer