apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cluster-name: stg
    app: stg-timescaledb
    role: replica
    monitoring: prometheus
  name: dm-stg-timescaledb-ha-replica
  namespace: monitoring
spec:
  jobLabel: metadata.name
  namespaceSelector:
    matchNames:
    - dm-stg
  podMetricsEndpoints:
  - interval: 30s
    port: pg-exporter
  selector:
    matchLabels:
      cluster-name: stg
      app: stg-timescaledb
      role: replica
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cluster-name: stg
    app: stg-timescaledb
    role: master
    monitoring: prometheus
  name: dm-stg-timescaledb-ha-master
  namespace: monitoring
spec:
  jobLabel: metadata.name
  namespaceSelector:
    matchNames:
    - dm-stg
  podMetricsEndpoints:
  - interval: 30s
    port: pg-exporter
  selector:
    matchLabels:
      cluster-name: stg
      app: stg-timescaledb
      role: master