# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  annotations:
    metallb.universe.tf/allow-shared-ip: key-to-share-192.168.11.246
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    role: slave
spec:
  ports:
  - name: mysql
    targetPort: 3306
    port: 3307
  type: LoadBalancer
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: cta-mysql-1
  loadBalancerIP: 192.168.11.246
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  annotations:
    metallb.universe.tf/allow-shared-ip: key-to-share-192.168.11.246
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    role: master
spec:
  ports:
  - name: mysql
    port: 3306
  type: LoadBalancer
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: cta-mysql-0
  loadBalancerIP: 192.168.11.246