apiVersion: batch/v1
kind: CronJob
metadata:
  name: prd-pgdata-backup
spec:
  schedule: "0 22 * * *" # utc
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-restore
            image: timescale/timescaledb:2.4.0-pg12
            imagePullPolicy: IfNotPresent
            command: 
            - sh 
            - -c 
            - sleep 1m && bash -x /pgscripts/prd-pgdata-backup.sh;
            env:
            - name: PGUSER
              value: django_admin
            - name: PGPASSWORD
              value: django_admin
            - name: PGHOST
              value: 'datamaster.timescaledb.svc.cluster.local'
            - name: PGPORT
              value: '5432'
            - name: master_db
              value: 'dm_test'
            - name: ROOT_DIR
              value: '/mnt'
            volumeMounts:
            - name: static-nas-timescaledb
              subPath: pg_backup/logical
              mountPath: /mnt
            - name: pgscripts
              mountPath: /pgscripts
          restartPolicy: Never
          volumes:
          - name: static-nas-timescaledb
            persistentVolumeClaim:
              claimName: static-nas-timescaledb
          - name: pgscripts
            configMap:
              name: pgscripts
      backoffLimit: 0
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prd-xml-pgdata-backup
spec:
  schedule: "0 6 * * 6" #utc
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pg-restore
            image: timescale/timescaledb:2.4.0-pg12
            imagePullPolicy: IfNotPresent
            command: 
            - sh 
            - -c 
            - sleep 1m && bash -x /pgscripts/prd-xml-pgdata-backup.sh;
            env:
            - name: PGUSER
              value: django_admin
            - name: PGPASSWORD
              value: django_admin
            - name: PGHOST
              value: 'datamaster.timescaledb.svc.cluster.local'
            - name: PGPORT
              value: '5432'
            - name: master_db
              value: 'dm_test'
            - name: ROOT_DIR
              value: '/mnt'
            volumeMounts:
            - name: static-nas-timescaledb
              subPath: timescaledb
              mountPath: /mnt
            - name: pgscripts
              mountPath: /pgscripts
          restartPolicy: Never
          volumes:
          - name: static-nas-timescaledb
            persistentVolumeClaim:
              claimName: static-nas-timescaledb
          - name: pgscripts
            configMap:
              name: pgscripts
      backoffLimit: 0