resources:
- cronjob.yaml

namespace: timescaledb

configMapGenerator:
- name: pgscripts
  files:
  - ./scripts/prd-pgdata-backup.sh
  - ./scripts/prd-xml-pgdata-backup.sh
  options:
    disableNameSuffixHash: true
