apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hk-aliyun-nas-pvc
  namespace: dm-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: hk-aliyun-nas-pv
  storageClassName: ''
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hk-aliyun-nas-pv
  namespace: dm-dev
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 12b63749986-vvr1.cn-hongkong.nas.aliyuncs.com
    path: /
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3
  volumeMode: Filesystem