apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-ng
spec:
  selector:
    matchLabels:
      app: mirror-ng
  template:
    metadata:
      labels:
        app: mirror-ng
    spec:
      volumes:
      - name: mirror-conf
        configMap:
          name: mirror-conf
      containers:
      - name: mirror-ng
        image: nginx:1.21.3
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/mirror.conf
          name: mirror-conf
          subPath: mirror.conf